language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
deploy:
  provider: cloudfoundry
  username: diego126.tn@gmail.com
  password:
    secure: T3GiX3eh+a6vTeCT1VHG/KsVC/mCY4eYlMvKEg+TobeQqCw4sNtahmHDHxK/6poObDCGBxPc9EDtOe6xCJdUSnVX6nkC40apzLkHiiKvTn3fmhpoNjKV51mEdcsTrrIH4yuGXzxjLolDSAf/86cwGI8IUVUDkQ+lDcoqPpMzRknpewIFkkfwW6tESIUWX6H/bWxVgizSbmReRAKRzLJENkIAyU1Wry7mv6c2EDhJybzNUvF8xrY9OaYVMNBu5TJH+4SjQvZYBJYY8tVzYvOh4j5391iTDQ/JoCv08lxtQa3UQ2GpfD0YH1MynS/fHIfaor7uFbtRP11uW/z0++AiiTZtSsN0cj/VL+y/zkIhMdP7kn9itHNjRgQnfG44dkDkzNcDQHEZmDKbhIRoX6oCfISklxD9mOhYl/WyExtJntOYV4yuGucTFPHvLiH1MwfXhPu3x+1Ri6C4PuZ/zpFEO9vGiEpkQJ0Q/zevnSq4Vu5AwcBbvAIknjWkzY7x5STRu/uHuX0zqlH/v6ptzzM9tG2ePqJvLgUc1W0RAUvrJrR9eCSFjyN9nrbzEAxZs8Gtu7gjunFD6DnYCcAKeRygAKYWQlmJa/xSAKNYbap2MiY6klhIsMNDyEXJlrTJwMqPw0uud1Xu23ijSJ3c1oYprYFw+BGHICHMabkCoE69zno=
  api: https://apiads.run.pivotal.io
  organization: maestria-fisi
  space: development
