language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
deploy:
  provider: cloudfoundry
  username: diego126.tn@gmail.com
  password:
    secure: ZUvN0iT5U6hHKPCuIaDpuURB+vnLkG+9xPlVaaYp7F+KOc0cqcQVigmCf9eXnF5GzcBafaGRSwDZDgrNuAVc9mnGIIc6LRsGGfGmJjGsJkNF/C/dXChAEE3jzHB2h78e+i6RklM/QPUUoEE14LAXi7quoiMLOLX5iWC34wvwwS/MrcIdKE3L7xhDyOkZJpon3JAo3zprEbKu6gdaBsyfNPcXvgHRLDdXiuus7GRndQuodEOfnsnErqvn2HNyop9m1lsvI2lnuxO6dx22UXfo+KbDmxN5iTj4OmMOYormHIRSmJFw8kg9MEydx6rneOUs6mi8caOXVyJPZ9OV4ayi7YZRGHnmvAdjlt/udYPFQIyP79CbEUZLjk2t+t/sR+UZgCwIKgc9nGMLk0sNNvHR6H2k1bAF+5YOU3Vh8MsNH5wAMJSEmI2l9UtitEcKqpg/uKGPiFKBmo9uuGYZqURXio9M6GlYlqvstjDz9VIryuii0rRxQtU4nh0Q12vYYn14TxyR6H03K0r4Q4ejTmsz0EkGqNxCRALgvGTBIm0aZoipVKxOZ3f21Qmpzcbme5yM2yiuN2xbnSS9s9IYd+3UAJa53pVTO5DL9a2es4h1Y5B+tgxxj3wILNJgQj6qb+L35cN8AxameRNFfOjpFqTKWQwRGTuprmwjxbK+Q+huosA=
  api: https://api.run.pivotal.io
  organization: maestria-fisi
  space: development
