language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
env:
  global:
    secure: N1uQIB5zESApzxnISt02KglXuI5egRI5d/lu94AVqu1cQwHLl2vE+HfhvZiRGWzyeuCFSIalSdvis2g8k/MGF5KshLBxM4J/XTIrDP9JxJyauXPRPU4iJVl5z8TVGpzirwvEIu12RQaDzD3qzsLzBdfdnayQz9QB9yTuNebaUCB1/5ylJOjNE/6l2Mz4XK5wko2vxlObT1lktyqYXNo+w/5/d/x8FQsruEO35dVLbsT6VNkJuBOoLoH2DmHasU1j9twHpLu0lHFa9bEdoAU1EK9xDjRZnIvsjfH/V8V9ae2PrNoks6JUvfVSIKNDEkcI9GuMrI16Q4Hm0y5tQdc7uf+2WA3U56vlRmFe1OzYKT9Nwrt3yB2yltDGUxHI/UCPfNmHPCHHvYRIRsLmzjLG7Ygv5IbMQVvp0RzA69I0XWbAF0yidEDbjWSx5BzipoQmXBmKA7eeakFcb8mU+0cswjnCw7O4madrwjUBozetRPCI/TkRFTxt+GayWfqJaKOFc2jSelQYNZARtCcwjqOTadQYzifoMIitDr4WBoGLoNky1h7igwVDh0BJno9gj8JmGZpub0S2BGhfseB2RobFipJU49HVOHG0hj471hR5D4UWFaGhxeEoCvfacYXXF5o5ywuwhGfKkecZlkU3igw9/sDHaaiXlMUBRx/v9/c1HIs=
deploy:
  provider: cloudfoundry
  username: diego126.tn@gmail.com
  password:
    secure: N1uQIB5zESApzxnISt02KglXuI5egRI5d/lu94AVqu1cQwHLl2vE+HfhvZiRGWzyeuCFSIalSdvis2g8k/MGF5KshLBxM4J/XTIrDP9JxJyauXPRPU4iJVl5z8TVGpzirwvEIu12RQaDzD3qzsLzBdfdnayQz9QB9yTuNebaUCB1/5ylJOjNE/6l2Mz4XK5wko2vxlObT1lktyqYXNo+w/5/d/x8FQsruEO35dVLbsT6VNkJuBOoLoH2DmHasU1j9twHpLu0lHFa9bEdoAU1EK9xDjRZnIvsjfH/V8V9ae2PrNoks6JUvfVSIKNDEkcI9GuMrI16Q4Hm0y5tQdc7uf+2WA3U56vlRmFe1OzYKT9Nwrt3yB2yltDGUxHI/UCPfNmHPCHHvYRIRsLmzjLG7Ygv5IbMQVvp0RzA69I0XWbAF0yidEDbjWSx5BzipoQmXBmKA7eeakFcb8mU+0cswjnCw7O4madrwjUBozetRPCI/TkRFTxt+GayWfqJaKOFc2jSelQYNZARtCcwjqOTadQYzifoMIitDr4WBoGLoNky1h7igwVDh0BJno9gj8JmGZpub0S2BGhfseB2RobFipJU49HVOHG0hj471hR5D4UWFaGhxeEoCvfacYXXF5o5ywuwhGfKkecZlkU3igw9/sDHaaiXlMUBRx/v9/c1HIs=
  api: https://api.run.pivotal.io
  organization: maestria-fisi
  space: development
