language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
deploy:
  provider: cloudfoundry
  username: diego126.tn@gmail.com
  password:
    secure: a5CH7BSKhV5sE9AtIxdpxWnN06Xp1jC+MhCcppiD9dB4CCdCMmUrKvgyccRLL6TaF+yzGrQ8NJDW5gN6gvTWNeB7sDf7QFCAAYIIuQkPi+AwnrAxSIHcHm36/wsvHZSrMUk0OQ9ft+sizAiNar/6EWDevpIc0v9lESp7B+yy3YJEasYnkeA+fwp/C1QqkUKpLZHgCV1FdzDgkmNutBBN5sNGFEmQWMi2arzRPQaLS5SrXCeChvQ0XYbRwoDdtn/c6d5Lq1rYnRL9y3BAZMZaQZIdANf7DwYX98WVHPyM6TC9lPhb/O25K1lJ94yYC/YhmBawD9f2p+hpUNZKNAQIUN9waucD+rxwk9qx48ISJbf2XF3LJ1H0/4CcM5c9dxGtVACmweEW/WyViW6Z8NaDOBEsdvsnUJ+gE19vLYBVwhdYM3Kk+oRsGewW29qxtD90waP45bv1LCUO/35QGExmDv/eg2dkv1KuKp1gp0B+hbZoqYHIV9mbOjeQm6q9SQzNHJpKiTAanRS2c77yQ5EAKpkmi9cXnrSVjJJxcijZkU2n9ZJqHaJju4KZ5ev/1upLlNmPLddKXyCQfI8CUvqHQUQ6PH1mHCle4WMkYpNmSRhL0bebGzUJLCWwCo2MVWkoYxdyTRxQnfNKW1HrNEej8JYWxIXdrRaqGZvsF6kHP7g=
  api: https://api.run.pivotal.io
  organization: maestria-fisi
  space: development
