language: java
sudo: true
jdk: oraclejdk8
script: env && ./mvnw package -B
before_install:
- chmod +x mvnw
install:
- mvn -N io.takari:maven:wrapper
- "./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V"
deploy:
  provider: cloudfoundry
  username: diego126.tn@gmail.com
  password:
    secure: nPiHmI/hlfFJFfvUlRM4nw3BYnQMPJr1U+iykyW5oxIMo+WoZk4V3QQDAAtz7zB47rEnNKtvZ2EC4fxZlgNIU6gns4ZvjW2Cygo9EDgIsgtgPzueVnxkKFQe6UKDlUqjsfIHjTDegsdsgFQT/m+pGtd8Ba+3C5TBR2m6GIyE1Hqs/b06PWpWO++o1g+qDVwJbUudYIF7aEwjdJpya+ArpaQ7KbqXpQjDaJuzwN2upSXxrh+A6kAvXWCOhU8Oxb4SorLyUDZrVHi3+AJUZjT+yQ3C432H7kNNt2IjboPPkQB53NQHQZH0vMupkqPqWdZD82jTZDTUuipZeKz8g2mNlzZVmwHNLzneaDRHapjGN5Wdlgr06bTOfoktSwafyW0Aj6CPENhZWfhGV5oHewDORmpNUhPd4pOU6IwEpmSNfPEmN+iY5eQNaXlDtRL09sCI//zUsvB6aQYFjQBWzCfUv3UdNg6foSMWoKNsh/NOE+2YisGs52yUf4bElhICSwnQ9rpEICg1bNEQ/HZ+mwdEPD1ft0EQh2J5eQt20hUYb9qnh10HUIPd3Py9tOQ3RWVO6HxwnWOFqRtWGWHnZk3+/RF0ivKC+6lOuSjXFtncAlRBkeE5kUl2lvfV+gquq2y/JEOKC7flBBfeqtlZpwGiRxeVJ2vDVKsU7fo5VQnPSJw=
  api: https://api.run.pivotal.io
  organization: maestria-fisi
  space: development
